services:
  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    ports:
      - "8847:8000"
    environment:
      - WHISPER__MODEL=small
      - WHISPER__DEVICE=cpu

  voicevox:
    image: voicevox/voicevox_engine
    platform: linux/amd64
    ports:
      - "50847:50021"

  db:
    image: postgres:16
    ports:
      - "5847:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avatar
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
